import { index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'

export const users = sqliteTable('users', {
  id: text('id').primaryKey(), email: text('email').notNull().unique(), displayName: text('display_name').notNull(), passwordHash: text('password_hash').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), createdAt: integer('created_at', { mode: 'timestamp' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
})
export const permissions = sqliteTable('permissions', { id: text('id').primaryKey(), code: text('code').notNull().unique(), label: text('label').notNull() })
export const userPermissions = sqliteTable('user_permissions', { userId: text('user_id').notNull().references(() => users.id), permissionId: text('permission_id').notNull().references(() => permissions.id), grantedAt: integer('granted_at', { mode: 'timestamp' }).notNull() }, (table) => [uniqueIndex('user_permissions_unique').on(table.userId, table.permissionId)])
export const sessions = sqliteTable('sessions', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(() => users.id), tokenHash: text('token_hash').notNull().unique(), expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, (table) => [index('sessions_token_hash_idx').on(table.tokenHash)])
export const invites = sqliteTable('invites', { id: text('id').primaryKey(), email: text('email').notNull(), tokenHash: text('token_hash').notNull().unique(), permissionsJson: text('permissions_json').notNull(), expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(), acceptedAt: integer('accepted_at', { mode: 'timestamp' }), createdBy: text('created_by').notNull().references(() => users.id) })

// Positions are percentages, retained for a future free-layout editor. The MVP
// renders operational tables as a predictable CSS grid instead.
export const zones = sqliteTable('zones', { id: text('id').primaryKey(), name: text('name').notNull() })
export const tables = sqliteTable('tables', { id: text('id').primaryKey(), zoneId: text('zone_id').references(() => zones.id), name: text('name').notNull(), capacity: integer('capacity').notNull().default(4), posX: real('pos_x').notNull().default(0), posY: real('pos_y').notNull().default(0), shape: text('shape', { enum: ['square', 'round'] }).notNull().default('square'), status: text('status', { enum: ['trong', 'dang_phuc_vu', 'dat_truoc', 'can_don'] }).notNull().default('trong') }, (table) => [uniqueIndex('tables_zone_name_unique').on(table.zoneId, table.name)])

export const categories = sqliteTable('categories', { id: text('id').primaryKey(), name: text('name').notNull(), sortOrder: integer('sort_order').notNull().default(0), active: integer('active', { mode: 'boolean' }).notNull().default(true) })
export const menuItems = sqliteTable('menu_items', { id: text('id').primaryKey(), categoryId: text('category_id').references(() => categories.id), name: text('name').notNull(), description: text('description').notNull().default(''), imageKey: text('image_key'), active: integer('active', { mode: 'boolean' }).notNull().default(true), createdAt: integer('created_at', { mode: 'timestamp' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull() })
export const menuVariants = sqliteTable('menu_variants', { id: text('id').primaryKey(), menuItemId: text('menu_item_id').notNull().references(() => menuItems.id), name: text('name').notNull(), price: integer('price').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), sortOrder: integer('sort_order').notNull().default(0) })
export const modifierGroups = sqliteTable('modifier_groups', { id: text('id').primaryKey(), name: text('name').notNull(), minSelections: integer('min_selections').notNull().default(0), maxSelections: integer('max_selections').notNull().default(1) })
export const modifiers = sqliteTable('modifiers', { id: text('id').primaryKey(), groupId: text('group_id').notNull().references(() => modifierGroups.id), name: text('name').notNull(), priceDelta: integer('price_delta').notNull().default(0), active: integer('active', { mode: 'boolean' }).notNull().default(true) })
export const variantModifierGroups = sqliteTable('variant_modifier_groups', { variantId: text('variant_id').notNull().references(() => menuVariants.id), groupId: text('group_id').notNull().references(() => modifierGroups.id) }, (table) => [uniqueIndex('variant_modifier_groups_unique').on(table.variantId, table.groupId)])
export const combos = sqliteTable('combos', { id: text('id').primaryKey(), menuItemId: text('menu_item_id').notNull().references(() => menuItems.id), price: integer('price').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true) })
export const comboComponents = sqliteTable('combo_components', { id: text('id').primaryKey(), comboId: text('combo_id').notNull().references(() => combos.id), variantId: text('variant_id').notNull().references(() => menuVariants.id), quantity: integer('quantity').notNull().default(1) })

export const ingredients = sqliteTable('ingredients', { id: text('id').primaryKey(), name: text('name').notNull().unique(), unit: text('unit').notNull(), reorderPoint: real('reorder_point').notNull().default(0), active: integer('active', { mode: 'boolean' }).notNull().default(true) })
export const recipes = sqliteTable('recipes', { id: text('id').primaryKey(), variantId: text('variant_id').notNull().references(() => menuVariants.id).unique(), revision: integer('revision').notNull().default(1), active: integer('active', { mode: 'boolean' }).notNull().default(true), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() })
export const recipeLines = sqliteTable('recipe_lines', { id: text('id').primaryKey(), recipeId: text('recipe_id').notNull().references(() => recipes.id), ingredientId: text('ingredient_id').notNull().references(() => ingredients.id), quantity: real('quantity').notNull() }, (table) => [uniqueIndex('recipe_lines_unique').on(table.recipeId, table.ingredientId)])
export const suppliers = sqliteTable('suppliers', { id: text('id').primaryKey(), name: text('name').notNull().unique(), phone: text('phone'), note: text('note').notNull().default(''), active: integer('active', { mode: 'boolean' }).notNull().default(true) })
export const inventoryLots = sqliteTable('inventory_lots', { id: text('id').primaryKey(), ingredientId: text('ingredient_id').notNull().references(() => ingredients.id), supplierId: text('supplier_id').references(() => suppliers.id), receivedAt: integer('received_at', { mode: 'timestamp' }).notNull(), expiresAt: integer('expires_at', { mode: 'timestamp' }), originalQuantity: real('original_quantity').notNull(), remainingQuantity: real('remaining_quantity').notNull(), unitCost: integer('unit_cost').notNull(), note: text('note').notNull().default('') }, (table) => [index('inventory_lots_fifo_idx').on(table.ingredientId, table.receivedAt)])
export const inventoryMovements = sqliteTable('inventory_movements', { id: text('id').primaryKey(), ingredientId: text('ingredient_id').notNull().references(() => ingredients.id), lotId: text('lot_id').references(() => inventoryLots.id), orderId: text('order_id'), type: text('type', { enum: ['receipt', 'sale', 'stocktake', 'adjustment', 'variance'] }).notNull(), quantityDelta: real('quantity_delta').notNull(), unitCost: integer('unit_cost'), reason: text('reason').notNull().default(''), actorId: text('actor_id').notNull().references(() => users.id), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, (table) => [index('inventory_movements_ingredient_idx').on(table.ingredientId, table.createdAt)])

export const orders = sqliteTable('orders', { id: text('id').primaryKey(), orderCode: text('order_code').notNull().unique(), idempotencyKey: text('idempotency_key').notNull().unique(), source: text('source', { enum: ['counter', 'takeaway', 'table'] }).notNull(), tableId: text('table_id').references(() => tables.id), note: text('note').notNull().default(''), status: text('status', { enum: ['draft', 'paid', 'completed', 'cancelled', 'sync_pending', 'inventory_variance'] }).notNull(), subtotal: integer('subtotal').notNull(), discountAmount: integer('discount_amount').notNull().default(0), total: integer('total').notNull(), cogs: integer('cogs').notNull().default(0), createdBy: text('created_by').notNull().references(() => users.id), paidAt: integer('paid_at', { mode: 'timestamp' }), createdAt: integer('created_at', { mode: 'timestamp' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull() }, (table) => [index('orders_table_status_idx').on(table.tableId, table.status), index('orders_created_at_idx').on(table.createdAt)])
export const orderLines = sqliteTable('order_lines', { id: text('id').primaryKey(), orderId: text('order_id').notNull().references(() => orders.id), menuItemId: text('menu_item_id'), variantId: text('variant_id'), nameSnapshot: text('name_snapshot').notNull(), variantSnapshot: text('variant_snapshot').notNull(), recipeSnapshot: text('recipe_snapshot').notNull(), unitPrice: integer('unit_price').notNull(), quantity: integer('quantity').notNull(), lineTotal: integer('line_total').notNull() })
export const orderLineModifiers = sqliteTable('order_line_modifiers', { id: text('id').primaryKey(), orderLineId: text('order_line_id').notNull().references(() => orderLines.id), nameSnapshot: text('name_snapshot').notNull(), priceDelta: integer('price_delta').notNull() })
export const orderDiscounts = sqliteTable('order_discounts', { id: text('id').primaryKey(), orderId: text('order_id').notNull().references(() => orders.id), type: text('type', { enum: ['percent', 'fixed'] }).notNull(), value: integer('value').notNull(), amount: integer('amount').notNull(), reason: text('reason').notNull(), actorId: text('actor_id').notNull().references(() => users.id), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() })
export const payments = sqliteTable('payments', { id: text('id').primaryKey(), orderId: text('order_id').notNull().references(() => orders.id).unique(), method: text('method', { enum: ['cash'] }).notNull().default('cash'), amount: integer('amount').notNull(), receivedAmount: integer('received_amount').notNull(), changeAmount: integer('change_amount').notNull(), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() })
export const offlineSyncRecords = sqliteTable('offline_sync_records', { idempotencyKey: text('idempotency_key').primaryKey(), orderId: text('order_id').notNull().references(() => orders.id), deviceId: text('device_id').notNull(), syncedAt: integer('synced_at', { mode: 'timestamp' }).notNull() })

export const timeEntries = sqliteTable('time_entries', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(() => users.id), checkInAt: integer('check_in_at', { mode: 'timestamp' }).notNull(), checkOutAt: integer('check_out_at', { mode: 'timestamp' }), approvedBy: text('approved_by').references(() => users.id), approvedAt: integer('approved_at', { mode: 'timestamp' }), note: text('note').notNull().default('') })
export const hourlyRateHistory = sqliteTable('hourly_rate_history', { id: text('id').primaryKey(), userId: text('user_id').notNull().references(() => users.id), hourlyRate: integer('hourly_rate').notNull(), effectiveAt: integer('effective_at', { mode: 'timestamp' }).notNull(), createdBy: text('created_by').notNull().references(() => users.id) })
export const payrollPeriods = sqliteTable('payroll_periods', { id: text('id').primaryKey(), startsOn: text('starts_on').notNull(), endsOn: text('ends_on').notNull(), status: text('status', { enum: ['open', 'closed'] }).notNull().default('open'), closedBy: text('closed_by').references(() => users.id), closedAt: integer('closed_at', { mode: 'timestamp' }) })
export const payrollEntries = sqliteTable('payroll_entries', { id: text('id').primaryKey(), periodId: text('period_id').notNull().references(() => payrollPeriods.id), userId: text('user_id').notNull().references(() => users.id), minutesWorked: integer('minutes_worked').notNull(), hourlyRateSnapshot: integer('hourly_rate_snapshot').notNull(), grossPay: integer('gross_pay').notNull(), adjustment: integer('adjustment').notNull().default(0), note: text('note').notNull().default('') }, (table) => [uniqueIndex('payroll_entries_period_user_unique').on(table.periodId, table.userId)])

export const auditLogs = sqliteTable('audit_logs', { id: text('id').primaryKey(), actorId: text('actor_id').references(() => users.id), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), action: text('action').notNull(), detailJson: text('detail_json').notNull(), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, (table) => [index('audit_logs_entity_idx').on(table.entityType, table.entityId), index('audit_logs_created_idx').on(table.createdAt)])
